---
apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
  namespace: docker-registry
spec:
  containers:
  - name: registry
    image: registry:2
    imagePullPolicy: Always
    ports:
      - containerPort: 5000
    volumes:
      - name: registry-data
        emptyDir: {}
  volumeMounts:
      - mountPath: /var/lib/registry
        name: registry-data
---
kind: Service
apiVersion: v1
metadata:
  name: registry
  namespace: docker-registry
spec:
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000